### ISSUE TITLE
Add template for pull request

### ISSUE THREAD

**Issue by blazing-panda** [eddie-energy/.github#3]
To ease the description and thereby understanding of pull requests, a template should be defined to suggest key information to be included.

Pull requests should reference the issue they resolve (also in part) and describe the proposed changes, to ease the review of its commits.

Documentation on defining templates on GitHub can be found [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates).

**Comment by fweingartshofer** [comment]
Closing since it's not relevant anymore.
